steps:
#This command is calling docker image from Google Container Repo "gcr.io/cloud-builders/docker"
#in arguments it is passing "build -t"
#and image name = gcr.io/$PROJECT_ID/hello-app
#and this image is built using contents from current directory "

#build docker container
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello-app', '.']

#This command is calling docker image from Google Container Repo "gcr.io/cloud-builders/docker"
#in arguments it is calling "push" action
#and passing image name = gcr.io/$PROJECT_ID/hello-app
#which pushes image to GCR
#push container to container registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/hello-app']
#This command is calling docker image from Google Container Repo "gcr.io/cloud-builders/docker"
#in arguments it is calling cloud run with deploy action
#and passing service name = cloudrunservice
#and image name = gcr.io/$PROJECT_ID/hello-app 
#This image should be there in GCR
#next argument passes region = 'us-central1' where it has to be deployed
#platform is managed and it allows unauthenticated access
#deploy to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cloudrunservice'
  - '--image'
  - 'gcr.io/$PROJECT_ID/hello-app'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
  - 'gcr.io/$PROJECT_ID/hello-app'
